title: ERAD 2016 Open Software Course
description: Things you need to know about the upcoming short course on community radar software at ERAD 2016
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
